apiVersion: v1
kind: Service
metadata:
  name: deterministic-rune-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: deterministic-rune
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081