apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-05-01T06:51:11Z"
  generation: 1
  labels:
    app: deterministic-rune
    manager: kubectl
    operation: Update
    time: "2022-05-01T06:51:11Z"
  name: deterministic-rune
  namespace: default
  resourceVersion: "10509"
  uid: da72d21b-8af8-459a-bb91-6e4701a227f0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deterministic-rune
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deterministic-rune
    spec:
      containers:
      - image: muninlabs.azurecr.io/deterministic-rune:v0.1
        imagePullPolicy: IfNotPresent
        name: deterministic-rune
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - containerPort: 8081
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}