apiVersion: apps/v1
kind: Deployment
metadata:
  name: deterministic-rune
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: deterministic-rune
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deterministic-rune
    spec:
      containers:
      - image: muninlabs.azurecr.io/deterministic-rune:v0.1
        imagePullPolicy: IfNotPresent
        name: deterministic-rune
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - containerPort: 8081