apiVersion: v1
kind: Service
metadata:
    name: "deterministicruneaks-f71b"
    labels:
        app: "deterministicruneaks-f71b"
spec:
    type: LoadBalancer
    ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
    selector:
        app: "deterministicruneaks-f71b"